package try_catch;
import java.lang.Exception;

public class Main {
public static void main(String[] args) {
	
	try{
		int a = 10/0;
	}
	catch(ArithmeticException arithmeticException) {}
	
	
}
}
